language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools


    # The SDK version used to compile your project
    - android-32

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - touch local.properties
script:
  - ./gradlew clean build jacocoTestReleaseUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)